FROM rust:1.82-slim AS rust

RUN cargo install --locked eza

FROM golang:1.25-alpine AS golang

RUN go install github.com/joshmedeski/sesh/v2@latest

FROM ghcr.io/kevindurb/fedora-box

COPY --from=rust /usr/local/cargo/bin/eza /usr/bin/
COPY --from=golang /go/bin/sesh /usr/bin/

RUN dnf copr enable atim/lazygit -y \
  && dnf copr enable atim/starship -y \
  && dnf install --assumeyes \
    bat \
    btop \
    difftastic \
    direnv \
    duf \
    entr \
    fastfetch \
    fzf \
    gh \
    git \
    git-delta \
    git-extras \
    go-task \
    golang \
    htop \
    httpie \
    jq \
    lazygit \
    lolcat \
    make \
    ncdu \
    nebula \
    neovim \
    nyancat \
    ollama \
    ping \
    prettyping \
    ps \
    pssh \
    pv \
    python-pip \
    python3-pip \
    ripgrep \
    starship \
    tig \
    tldr \
    tmux \
    wc \
    yq \
    zoxide \
    && dnf clean all
