FROM ghcr.io/kevindurb/fedora-box

RUN dnf copr enable atim/lazygit -y \
  && dnf copr enable atim/starship -y \
  && dnf install --assumeyes \
    bat \
    duf \
    entr \
    fastfetch \
    fzf \
    gh \
    git \
    git-delta \
    git-extras \
    go-task \
    golang \
    htop \
    httpie \
    jq \
    lazygit \
    lolcat \
    make \
    ncdu \
    neovim \
    nyancat \
    ping \
    prettyping \
    ps \
    pv \
    python-pip \
    python3-pip \
    ripgrep \
    starship \
    tig \
    tldr \
    tmux \
    wc \
    yq \
    zoxide \
    && dnf clean all
