FROM quay.io/fedora/fedora:43

RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  && dnf install -y HandBrake \
  && dnf clean all

ENTRYPOINT ["/usr/bin/HandBrakeCLI"]
