FROM python:3.9 as build

RUN apt-get update
RUN apt-get install -y cmake gcc g++ libgl1 libglib2.0-0
RUN pip install -q super-gradients==3.7.1
RUN sed -i 's/sghub.deci.ai/sg-hub-nv.s3.amazonaws.com/' /usr/local/lib/python3.9/site-packages/super_gradients/training/pretrained_models.py \
    && sed -i 's/sghub.deci.ai/sg-hub-nv.s3.amazonaws.com/' /usr/local/lib/python3.9/site-packages/super_gradients/training/utils/checkpoint_utils.py

COPY ./build_model.py ./
RUN python ./build_model.py

FROM scratch

COPY --from=build /yolo_nas_s.onnx /
