FROM docker.io/library/debian:12

RUN apt update \
  && apt install -y wget \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
ENTRYPOINT ["/.dropbox-dist/dropboxd"]
