FROM docker.io/library/debian:12

RUN apt update \
  && apt install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN useradd -m dropbox
USER dropbox
WORKDIR /home/dropbox

RUN wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
ENTRYPOINT ["/home/dropbox/.dropbox-dist/dropboxd"]
